version: 2
updates:
  - package-ecosystem: "github-actions"
    # Check for updates to GitHub Actions every week
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:05"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    target-branch: "master"
    assignees:
      - thomas-nilsson-irfu
